[build]
  base = "."
  publish = "PWA/BusinessFieldOps/dist"
  command = "pnpm --dir PWA/BusinessFieldOps install --frozen-lockfile && pnpm --dir PWA/BusinessFieldOps run prepare && pnpm --dir PWA/BusinessFieldOps run build"

[context.deploy-preview]
  command = "pnpm --dir PWA/BusinessFieldOps install --frozen-lockfile && pnpm --dir PWA/BusinessFieldOps run prepare && pnpm --dir PWA/BusinessFieldOps run build"

[context.branch-deploy]
  command = "pnpm --dir PWA/BusinessFieldOps install --frozen-lockfile && pnpm --dir PWA/BusinessFieldOps run prepare && pnpm --dir PWA/BusinessFieldOps run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200